### PR TITLE
Add alias for "git pull --rebase"

### PR DESCRIPTION
**Pull request by jawshooah**
[Review on Reviewable](https://reviewable.io/reviews/ndbroadbent/scm_breeze/160)

### CODE REVIEW

**Comment by Tr4pSt3R** [comment]
:+1:

**Comment by jeffbyrnes** [comment]
:+1:

**Comment by tuxinaut** [comment]
Any concerns or why is this pull request still not merged?

**Comment by ndbroadbent** [comment]
Sorry, the only reason is that I don't really enjoy maintaining this project anymore. But I'll merge this one now, hope that helps!

**Comment by tuxinaut** [comment]
@ndbroadbent thx for merging. Yes OK I saw see hint on the frontage. What is about a owner / maintainer change?

**Comment by ghthor** [comment]
@ndbroadbent I'll throw myself in as a candidate for maintaining scm breeze.

**Pull request merged**
